# Generated by Django 3.1 on 2020-09-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uybozor', '0005_auto_20200912_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
