# Generated by Django 3.1 on 2020-09-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uybozor', '0007_announcement_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='username',
            field=models.CharField(default='Rahmet97', max_length=30),
            preserve_default=False,
        ),
    ]
